# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedb',
            name='fileName',
            field=models.CharField(max_length=20),
        ),
    ]
