# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedb',
            name='className',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='filedb',
            name='fileName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='filedb',
            name='fileObj',
            field=models.FileField(upload_to='./static/uploads/'),
        ),
    ]
