# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_completeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
