# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160521_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.QuizChoices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
