# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160521_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='choices',
        ),
        migrations.AddField(
            model_name='quizchoices',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Quiz'),
            preserve_default=False,
        ),
    ]
