# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160522_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
