# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activeQuiz',
            field=models.BooleanField(default=False),
        ),
    ]
